# Generated by Django 3.1.3 on 2020-11-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.PositiveIntegerField(verbose_name='закупочная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.PositiveIntegerField(verbose_name='розничная цена'),
        ),
    ]
